import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  es: {
    heroTitle: 'JUNIOR LUGO',
    heroSubtitle: 'Producción musical para artistas globales. Más allá del sonido, creamos tu legado.',
    storeBtn: 'Ir a Tienda',
    prodBtn: 'Producción Integral',
    mixBtn: 'Mezcla & Mastering',
    arrangementsBtn: 'Arreglos Musicales',
    sheetMusicBtn: 'Partituras Pro',
    navCatalog: 'Catálogo de Productos',
    navServices: 'Servicios',
    navGallery: 'Galería',
    dashboard: 'Dashboard',
    logout: 'Cerrar Sesión',
    backToHome: 'Volver al Inicio',
    footerServices: 'SERVICIOS',
    footerMarketplace: 'MARKETPLACE',
    footerContact: 'CONTACTO',
    waDirect: 'WhatsApp Directo',
    allRights: 'Todos los derechos reservados.',
    myHistory: 'MI TRAYECTORIA',
    xpProfessional: 'Experiencia Profesional',
    readyToStart: '¿LISTO PARA EMPEZAR?',
    talkWA: 'Hablar por WhatsApp',
    creditsFull: 'VER CRÉDITOS COMPLETOS',
    misCompras: 'Mis Compras',
    metodoPago: 'Método de Pago',
    miInfo: 'Mi Información',
    inicio: 'Inicio',

    // Landing
    catalogTitle: 'CATÁLOGO DE PRODUCTOS',
    catalogSubtitle: 'INSTRUMENTALES EXCLUSIVOS',
    listenBtn: 'ESCUCHAR',
    buyBtn: 'COMPRAR',
    viewFullCatalog: 'VER CATÁLOGO COMPLETO +',
    multitracksTitle: 'MULTITRACKS EN VENTA',
    multitracksSubtitle: 'Sesiones profesionales de estudio listas para tu motor',
    addBtn: 'AGREGAR',
    viewAllMultitracks: 'VER TODOS LOS MULTITRACKS',
    productionServices: 'SERVICIOS DE PRODUCCIÓN',
    whatCanIDo: '¿QUÉ PUEDO HACER POR TU MÚSICA?',
    musicProdTitle: 'Producción Musical',
    musicProdDesc: 'Desarrollo integral de canciones desde la idea inicial hasta el master final, trabajando cada proyecto bajo una sola visión artística y sonora.',
    moreInfo: 'Más Información →',
    mixProTitle: 'Mezcla Profesional',
    mixProDesc: 'Balanceo y procesamiento de todos los elementos de tu canción para lograr un sonido cohesivo, potente y competitivo.',
    masteringTitle: 'Masterización',
    masteringDesc: 'Preparación final de tu canción para distribución en plataformas digitales con el máximo nivel de calidad y volumen competitivo.',
    recordingTitle: 'Grabación de Voces',
    recordingDesc: 'Sesión de grabación vocal con dirección artística para capturar la mejor interpretación de cada canción.',
    visualsTitle: 'Visuales',
    studioExperience: 'Experiencia en el Estudio',
    viewFullGallery: 'Ver Galería Completa',
    processStages: 'ETAPAS DEL PROCESO',
    howWeWork: 'CÓMO TRABAJAMOS JUNTOS',
    preproductionTitle: 'PREPRODUCCIÓN',
    preproductionDesc: 'Definimos la dirección artística, estructura y concepto de la canción. Arreglos musicales con instrumentos virtuales como herramienta creativa.',
    productionTitle: 'PRODUCCIÓN',
    productionDesc: 'Grabación de instrumentos, voces y arreglos musicales. Sustitución de elementos virtuales por instrumentos reales buscando la mejor interpretación.',
    mixMasterTitle: 'MEZCLA Y MASTERING',
    mixMasterDesc: 'Pulir la visión artística del proyecto asegurando coherencia, claridad y calidad. Tu canción lista para subir a plataformas digitales.',
    sheetMusicTitle: 'PARTITURAS',
    sheetMusicDesc: 'Entrega de partituras profesionales para presentaciones en vivo con músicos en escena.',
    portfolioTitle: 'PORTAFOLIO',
    recentWorks: 'PRODUCCIONES Y TRABAJOS RECIENTES',
    viewAllPortfolio: 'VER TODO EL PORTAFOLIO',
    top10Title: 'Top 10 de este Mes',
    verPistas: 'Ver Pistas',
    moreTracksSoon: 'Más pistas próximamente...',
    connectWithMe: 'CONÉCTATE CONMIGO',
    followSocials: 'SÍGUEME EN MIS REDES PARA MÁS CONTENIDO',
    verifiedProfile: 'Perfil Verificado en Muso.ai',
    juniorBio: 'Especializado en Producción, Mezcla y Arreglos. Mi enfoque es llevar maquetas y demos a un nivel de competición global, respetando siempre la visión del artista.',
    readyToStartDesc: 'Transformemos tu idea en un sonido profesional. Contáctame directamente para hablar de tu proyecto.',
    contactDescription: 'Transformemos tu idea en un sonido profesional. Contáctame directamente para hablar de tu proyecto.',
    customServices: 'Servicios personalizados para artistas y bandas.',
    verCatalogo: 'Ver Catálogo Completo',

    // ProduccionIntegral
    prodIntegralTitlePart1: 'PRODUCCIÓN',
    prodIntegralTitlePart2: 'INTEGRAL',
    prodIntegralSubtitle: 'Llevamos tu música desde una simple idea o maqueta hasta un nivel de competición global en todas las plataformas.',
    startProject: 'INICIAR MI PROYECTO',
    highLevelService: 'Servicios de Alto Nivel',
    creativeProcess: 'EL PROCESO CREATIVO',
    whyChooseProd: '¿Por qué elegir Producción Integral?',
    whyChooseDesc: 'Contar con un solo productor que supervise todo el camino garantiza coherencia artística, ahorra tiempo y sobre todo, asegura que el resultado final sea exactamente lo que imaginaste (o incluso mejor).',
    arrangementsComp: 'Arreglos y Composición',
    arrangementsCompDesc: 'No solo creamos música, le damos forma. Desarrollamos arreglos modernos y emotivos que resaltan la esencia de tu canción.',
    vocalRecording: 'Grabación y Coach Vocal',
    vocalRecordingDesc: 'Dirigimos tus sesiones de grabación para obtener la mejor interpretación posible, cuidando la afinación, el timbre y la emoción.',
    nextHit: 'Hablemos de tu próximo éxito',
    nextHitDesc: 'Agenda una consultoría gratuita para analizar tu material y ver cómo podemos llevarlo al siguiente nivel.',
    writeWA: 'ESCRIBIR POR WHATSAPP',

    // MezclaMastering
    mixMasterHeroTitle: 'MEZCLA &',
    mixMasterHeroTitle2: 'MASTERING',
    mixMasterSubtitle: 'Sonido con estándar de competición internacional para tus canciones.',
    worldClassSound: 'Sonido de Clase Mundial',
    proMixingTitle: 'Mezcla Profesional',
    proMixingDesc: 'Equilibrio perfecto, claridad y profundidad para que cada elemento de tu arreglo brille con fuerza.',
    proMasteringTitle: 'Mastering de Radio',
    proMasteringDesc: 'El volumen y la consistencia necesarios para competir en plataformas digitales y radio global.',
    hybridProcess: 'Procesamiento Híbrido',
    hybridProcessDesc: 'Combinamos lo mejor del mundo analógico (calidez y textura) con la precisión digital (claridad y control).',
    listenPrev: 'ESCUCHA LA DIFERENCIA',
    before: 'ANTES',
    after: 'DESPUÉS',

    // ArreglosMusicales
    arrangementsHeroTitle: 'ARREGLOS',
    arrangementsHeroTitle2: 'MUSICALES',
    arrangementsSubtitle: 'Vestimos tu canción con la instrumentación perfecta para que destaque en cualquier género.',
    creativeArrangements: 'Arreglos Creativos',
    modernOrchestration: 'Orquestación Moderna',
    modernOrchestrationDesc: 'Desde cuerdas cinematográficas hasta sintetizadores de vanguardia, creamos el entorno perfecto para tu voz.',
    customInstrumentation: 'Instrumentación a Medida',
    customInstrumentationDesc: 'Grabación de instrumentos reales o programación MIDI de alta gama para lograr un sonido orgánico y profesional.',
    arrangementProcess: 'Nuestro Proceso de Arreglo',
    arrangementProcessDesc: 'Analizamos la armonía, el ritmo y la melodía de tu propuesta para expandirla y potenciar todas sus virtudes.',

    // PartiturasPro
    sheetMusicHeroTitle: 'PARTITURAS',
    sheetMusicHeroTitle2: 'PRO',
    sheetMusicSubtitle: 'Documentación musical profesional para bandas, orquestas y presentaciones en vivo.',
    precisionDocumentation: 'Documentación de Precisión',
    readableCharts: 'Charts de Lectura Rápida',
    readableChartsDesc: 'Partituras claras y optimizadas para que tus músicos puedan interpretar la canción en su primera lectura.',
    fullOrchestration: 'Transcripción y Orquestación',
    fullOrchestrationDesc: 'Pasamos cualquier audio a papel musical con precisión quirúrgica, respetando cada detalle del arreglo original.',
    livePerformance: 'Prueba de Escenario',
    livePerformanceDesc: 'Garantizamos que el material entregado sea funcional para presentaciones en vivo y sesiones de grabación.',
  },
  en: {
    heroTitle: 'JUNIOR LUGO',
    heroSubtitle: 'Music production for global artists. Beyond sound, we create your legacy.',
    storeBtn: 'Go to Store',
    prodBtn: 'Full Production',
    mixBtn: 'Mixing & Mastering',
    arrangementsBtn: 'Musical Arrangements',
    sheetMusicBtn: 'Pro Sheet Music',
    navCatalog: 'Product Catalog',
    navServices: 'Services',
    navGallery: 'Gallery',
    dashboard: 'Dashboard',
    logout: 'Log Out',
    backToHome: 'Back to Home',
    footerServices: 'SERVICES',
    footerMarketplace: 'MARKETPLACE',
    footerContact: 'CONTACT',
    waDirect: 'Direct WhatsApp',
    allRights: 'All rights reserved.',
    myHistory: 'MY CAREER',
    xpProfessional: 'Professional Experience',
    readyToStart: 'READY TO START?',
    talkWA: 'Talk on WhatsApp',
    creditsFull: 'VIEW FULL CREDITS',
    misCompras: 'My Purchases',
    metodoPago: 'Payment Method',
    miInfo: 'My Info',
    inicio: 'Home',

    // Landing
    catalogTitle: 'PRODUCT CATALOG',
    catalogSubtitle: 'EXCLUSIVE INSTRUMENTALS',
    listenBtn: 'LISTEN',
    buyBtn: 'BUY',
    viewFullCatalog: 'VIEW FULL CATALOG +',
    multitracksTitle: 'MULTITRACKS FOR SALE',
    multitracksSubtitle: 'Professional studio sessions ready for your engine',
    addBtn: 'ADD',
    viewAllMultitracks: 'VIEW ALL MULTITRACKS',
    productionServices: 'PRODUCTION SERVICES',
    whatCanIDo: 'WHAT CAN I DO FOR YOUR MUSIC?',
    musicProdTitle: 'Music Production',
    musicProdDesc: 'Comprehensive development of songs from the initial idea to the final master, working each project under a single artistic and sonic vision.',
    moreInfo: 'More Information →',
    mixProTitle: 'Professional Mixing',
    mixProDesc: 'Balancing and processing of all elements of your song to achieve a cohesive, powerful and competitive sound.',
    masteringTitle: 'Mastering',
    masteringDesc: 'Final preparation of your song for distribution on digital platforms with the maximum level of quality and competitive volume.',
    recordingTitle: 'Vocal Recording',
    recordingDesc: 'Vocal recording session with artistic direction to capture the best performance of each song.',
    visualsTitle: 'Visuals',
    studioExperience: 'Studio Experience',
    viewFullGallery: 'View Full Gallery',
    processStages: 'PROCESS STAGES',
    howWeWork: 'HOW WE WORK TOGETHER',
    preproductionTitle: 'PRE-PRODUCTION',
    preproductionDesc: 'We define the artistic direction, structure and concept of the song. Musical arrangements with virtual instruments as a creative tool.',
    productionTitle: 'PRODUCTION',
    productionDesc: 'Recording of instruments, voices and musical arrangements. Substitution of virtual elements for real instruments seeking the best performance.',
    mixMasterTitle: 'MIXING & MASTERING',
    mixMasterDesc: 'Polishing the artistic vision of the project ensuring coherence, clarity and quality. Your song ready to upload to digital platforms.',
    sheetMusicTitle: 'SHEET MUSIC',
    sheetMusicDesc: 'Delivery of professional sheet music for live performances with musicians on stage.',
    portfolioTitle: 'PORTAFOLIO',
    recentWorks: 'RECENT PRODUCTIONS AND WORKS',
    viewAllPortfolio: 'VIEW ALL PORTFOLIO',
    top10Title: 'Top 10 this Month',
    verPistas: 'View Tracks',
    moreTracksSoon: 'More tracks coming soon...',
    connectWithMe: 'CONNECT WITH ME',
    followSocials: 'FOLLOW MY SOCIALS FOR MORE CONTENT',
    verifiedProfile: 'Verified Profile on Muso.ai',
    juniorBio: 'Specialized in Production, Mixing and Arrangements. My focus is to take demos and mockups to a global competition level, always respecting the artist\'s vision.',
    readyToStartDesc: 'Let\'s transform your idea into a professional sound. Contact me directly to discuss your project.',
    contactDescription: 'Let\'s transform your idea into a professional sound. Contact me directly to discuss your project.',
    customServices: 'Personalized services for artists and bands.',
    verCatalogo: 'View Full Catalog',

    // ProduccionIntegral
    prodIntegralTitlePart1: 'FULL',
    prodIntegralTitlePart2: 'PRODUCTION',
    prodIntegralSubtitle: 'We take your music from a simple idea or demo to a global competition level across all platforms.',
    startProject: 'START MY PROJECT',
    highLevelService: 'High-Level Services',
    creativeProcess: 'THE CREATIVE PROCESS',
    whyChooseProd: 'Why choose Full Production?',
    whyChooseDesc: 'Having a single producer oversee the entire process ensures artistic coherence, saves time, and above all, ensures that the final result is exactly what you imagined (or even better).',
    arrangementsComp: 'Arrangements and Composition',
    arrangementsCompDesc: 'We don\'t just create music, we shape it. We develop modern and emotional arrangements that highlight the essence of your song.',
    vocalRecording: 'Vocal Recording and Coaching',
    vocalRecordingDesc: 'We lead your recording sessions to get the best possible performance, taking care of tuning, timbre and emotion.',
    nextHit: 'Let\'s talk about your next hit',
    nextHitDesc: 'Schedule a free consultation to analyze your material and see how we can take it to the next level.',
    writeWA: 'WRITE VIA WHATSAPP',

    // MezclaMastering
    mixMasterHeroTitle: 'MIXING &',
    mixMasterHeroTitle2: 'MASTERING',
    mixMasterSubtitle: 'International competition standard sound for your songs.',
    worldClassSound: 'World Class Sound',
    proMixingTitle: 'Professional Mixing',
    proMixingDesc: 'Perfect balance, clarity and depth so that every element of your arrangement shines brightly.',
    proMasteringTitle: 'Radio Mastering',
    proMasteringDesc: 'The volume and consistency needed to compete on digital platforms and global radio.',
    hybridProcess: 'Hybrid Processing',
    hybridProcessDesc: 'We combine the best of the analog world (warmth and texture) with digital precision (clarity and control).',
    listenPrev: 'LISTEN TO THE DIFFERENCE',
    before: 'BEFORE',
    after: 'AFTER',

    // ArreglosMusicales
    arrangementsHeroTitle: 'MUSICAL',
    arrangementsHeroTitle2: 'ARRANGEMENTS',
    arrangementsSubtitle: 'We dress your song with the perfect instrumentation to make it stand out in any genre.',
    creativeArrangements: 'Creative Arrangements',
    modernOrchestration: 'Modern Orchestration',
    modernOrchestrationDesc: 'From cinematic strings to cutting-edge synths, we create the perfect environment for your voice.',
    customInstrumentation: 'Custom Instrumentation',
    customInstrumentationDesc: 'High-end MIDI programming or real instrument recording to achieve an organic and professional sound.',
    arrangementProcess: 'Our Arrangement Process',
    arrangementProcessDesc: 'We analyze the harmony, rhythm and melody of your proposal to expand it and enhance all its virtues.',

    // PartiturasPro
    sheetMusicHeroTitle: 'PRO SHEET',
    sheetMusicHeroTitle2: 'MUSIC',
    sheetMusicSubtitle: 'Professional musical documentation for bands, orchestras and live performances.',
    precisionDocumentation: 'Precision Documentation',
    readableCharts: 'Quick Reading Charts',
    readableChartsDesc: 'Clear and optimized sheet music so your musicians can interpret the song on their first read.',
    fullOrchestration: 'Transcription and Orchestration',
    fullOrchestrationDesc: 'We turn any audio into musical paper with surgical precision, respecting every detail of the original arrangement.',
    livePerformance: 'Stage Testing',
    livePerformanceDesc: 'We guarantee that the material delivered is functional for live performances and recording sessions.',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'es');

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'es' ? 'en' : 'es'));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
